config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get "/hello" => "welcome#index"
  get "/about" => "welcome#about"

  get "/hello/:name" => "welcome#greet", as: :greet

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  get "/questions/new" => "questions#new", as: :new_question#(this is a helper method, no need to hardcode)
  post "/questions" => "questions#create", as: :questions#(used more like a collection)

  get "/questions/:id" => "questions#show", as: :question
  get "/questions/:id/edit" => "questions#edit", as: :edit_question
  patch "/questions/:id" => "questions#update"
  delete "/questions/:id" => "questions#destroy"

  get "/questions" => "questions#index"
  resources :questions do
    get :search, on: :collection
    patch :mark_done, on: :member
    post :approve

    resources :answers, only: [:create, :destroy, :index]
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]

  end

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  namespace :api, defaults: {format: :json} do
  namespace :v1 do
    resources :questions, only: [:index, :show, :create]
  end
end

  resources :users, only: [:create, :new]

resources :sessions, only: [:new, :create, :destroy] do
  delete :destroy, on: :collection
end

resources :favorites, only: [:index]

get "/auth/twitter", as: :sign_in_with_twitter
get "/auth/twitter/callback" => "callbacks#twitter"

  root 'questions#index'

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  view_count :integer
#

class Question < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
  attr_accessor :tweet_it

  belongs_to :category
  belongs_to :user




  # This will establish a 'has_many' association with answers. This assumes
  # that your answer model has a 'question_id' integer field that references
  # the question. with has_many 'answers' must be plural (Rails convention).
  #  we must pass a 'dependent' option to maintain data integrity. The possible
  #  values you can give it are: :destroy or :nullify
  #  With :destroy: if you delete a question it will delte all associated answers
  #  With :nullify: if you delete a question it will ipdate the 'question_id' null
  #                 for all associated records (they won't get deleted)
  has_many :answers, dependent: :destroy
  # this enables us to access all the comments created for all the question's
  # answers. This generates a single SQL statment with 'INNER JOIN' to
  # accomplish it
  has_many :comments, through: :answers

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  has_many :favorites, dependent: :destroy
  has_many :favor_users, through: :favorites, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user




  #first form of validation
  # This will fail validations (so it won't create or save) if the title is
  # not provided
    validates :title, presence: true,
                      uniqueness: { case_sensitive: false},
                      length: {minimum: 3, maximum: 255}
    #how to change default message
    # DSL: Domain Specific Langugage
    # the code we use in here is completely valid Ruby code but the method naming
    # and arguments are specific to AvtiveRecord so we call this an AvtiveRecord
    # DSL
    validates(:body, {uniqueness: {message: "must be unique!"}})

    # this validates that the combination of the title and body is unique. Which
    # means the title doesn't have to be unique by itself and the body doesn't
    # have to be unique by itself. However, the combination of the two fields
    # must be unique
    # validates :title, uniqueness: {scope: :body}

    validates :view_count, numericality: {greater_than_or_equal_to: 0}

    #   validates :email,
    #             format: { with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }

    # this is using custom validation method, we must make sure that "no_monkey"
    # is a method available for our class. the method can be public or private
    # It's more likely we will have it a private method because we don't need
    # to use it outside this class.
    validate :no_monkey

    after_initialize :set_defaults
    before_save :capitalize_title

    # without an arguments scope :recent, lambda { order("created_at DESC").limit(5)}
    # with an arguments scope :recent, lambda { |x| order("created_at DESC").limit(x)}
    # you are able to combine query
    # you are able to give arguments to give you more flexibility
    def self.recent(number = 5)
      order("created_at DESC").limit(number)

    end

    def self.popular
      where("view_count > 10")
    end

    # Wildcard search by title or body
    # ordered by view_count in a descending order
    def self.search(term)
      # where(["title ILIKE ? or body ILIKE ?", "%#{term}%", "%#{term}%"])

      where(["title ILIKE ? or body ILIKE ?", "%" + term + "%", "%" + term + "%"]).
      order("view_count DESC").limit(10)

    end
    def category_name
      category.name if category
    end
    # delegate :full_name, to: :user, prefix: true <--------- this is a short to
    # acheiveing the same goal as below.
    def user_full_name
      user.full_name if user
    end

    def like_for(user)
      likes.find_by_user_id user
    end

    def favor_for(user)
      favorites.find_by_user_id user
    end

    def vote_for(user)
      votes.find_by_user_id user
    end

    def vote_result
      votes.up_count - votes.down_count
    end







    private
    def set_defaults
      self.view_count ||= 0
                      #(conditional operator, if it's not set use 0 )
    end

    # capitalize_title method is done after validation,
    # therefore, you don't need to worry about nil
    def capitalize_title
      self.title.capitalize!
    end


  def no_monkey
    if title && title.downcase.include?("monkey")
# errors method take two arguments first one is field, and what you want to print out
      errors.add(:title,"false")
    end
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::BaseController

  def create
    def create
      # params => {"question"=>{"title"=>"hello world", "body"=>"something here"}}
      # question       = Question.new
      # question.title = params[:question][:title]
      # question.body  = params[:question][:body]

      @question      = Question.new question_params
      @question.user = current_user
      if @question.save
        # all these formats are possible ways to redirect in Rails:
        # redirect_to question_path({id: @question.id})
        # redirect_to question_path({id: @question})
        # redirect_to @question
        flash[:notice] = "Question Created Successfully!"
        redirect_to question_path(@question)
      else
        # This will render app/views/questions/new.html.erb template
        # we need to be explicit about rendering the new template becuase the
        # default behaviour is to render `create.html.erb`
        # you can specify full path such as: render "/questions/new"
        flash[:alert] = "Question wasn't created. Check errors below"
        render :new
      end
    end
  end

  def index
    @questions = Question.order("created_at DESC").limit(10)
    # render json: @questions
    # will render /api/v1/questions/index.json.jbuilder
    # render json: @questions
  end

  def show
    @question = Question.find params[:id]
    # send JSON that has:
    # all attributes of the question
    # list of answers (JSON array)
    # list of tags (JSON array)
    render json: @question
  end

  def create
    question_params = params.require(:question).permit(:title, :body)
    question        = Question.new question_params
    question.user   = @user
    if question.save
      head :ok
    else
      render json: {errors: question.errors.full_messages}
    end
  end
end

app/controllers/questions_controller.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  view_count :integer
#

class QuestionsController < ApplicationController
  # This 'before_action' will call the 'find_question' method before executing
  # any other action.
  # We can specify :only or "except" to be more specific about the actions
  # which the before_action apply to
  # before_action :find_question, except: [:new, :create, :index]
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user, except: [:index, :show]

  before_action :authorize_user, only: [:edit, :update, :destory]



  def new
    @question = Question.new
  end

  def create
    # params => {"question"=>{"title"=>"hello world", "body"=>"something here"}}
  #  question       = Question.new
  #  question.title = params[:question][:title]
  #  question.body  = params[:question][:body]
#---------------------------------------------------------------------------------------------#
  # using params. require ensures that there is a key called 'question' in my
  # params. the 'permit' method will only allow paramsters that you explicitly
  # list, in this case: title and body
  # This is called a Strong parameter
  #  question_params = params.require(:question).permit([:title, :body])

  # We made a method!!!
#--------------------------------------------------------------------------------------------#
   @question = Question.new question_params
   @question.user = current_user
   # When you .save it will return 'save' or 'false'
   # if i need to access data use render, however, if you need new url to capture info use redirect
   if @question.save
     if @question.tweet_it
         client = Twitter::REST::Client.new do |config|
           config.consumer_key        = ENV["twitter_consumer_key"]
           config.consumer_secret     = ENV["twitter_consumer_secret"]
           config.access_token        = current_user.twitter_token
           config.access_token_secret = current_user.twitter_secret
         end
         client.update("New Question: #{@question.title}")
       end

    # All these formats are possible ways to redirect in Rails:
    #  redirect_to question_path({id: @question.id})
    #  redirect_to question_path({id: @question})
    #  redirect_to @question

    flash[:notice] = "Question Created Successfully!"
    redirect_to question_path(@question)
   else
   # This will render app/views/questions/new.html.erb template
   # we need to be explict about rendering the new template because the
   # default behavior is to render 'create.html.erb'
   # you can specify full path such as: render "/questions/new"
   flash[:alert] = "Question wasn't created. Check errors below"
   render :new
  end
 end
 # GET: /question/1
  def show
    @question.view_count += 1
    @question.save
    @answer = Answer.new
    respond_to do |format|
      format.html { render }
      format.json { render json: @question }
    end
  end
  # listings page
  def index
    @questions = Question.all
  respond_to do |format|
    format.html { render }
    format.json { render json: @questions.select(:id, :title, :view_count) }
  end
end

  def edit
    # we need to find the question that will be edited
    # This is a conditional where if the current_user does not match the
    # @question.user go back to the root_path
    if @question.user != current_user
      redirect_to root_path, alert: "access denied!"
    end

  end

  def update
    # we need to fetch the question first to update it
    # We call the update with sanitized params
    if @question.update question_params #This statement will return true or false(acting like .save)
    # we redirect to the question show page
      redirect_to(question_path(@question), {notice: "question updated"})
    else
      render :edit
    end


end

  def destroy
    # IF you use Delete, it will skip all the call backs and will delete the
    @question.destroy
    # we redirect to the index page
    redirect_to questions_path, notice: "Question Deleted!"

  end

  private

  def question_params
    # using params. require ensures that there is a key called 'question' in my
    # params. the 'permit' method will only allow paramsters that you explicitly
    # list, in this case: title and body
    # This is called a Strong parameter
    # we must use strong params to only allow updating the title / body

    params.require(:question).permit([:title, :body, :category_id, :tweet_it, {tag_ids: []}])
  end

  def find_question
    @question = Question.friendly.find params[:id]
    # Method of eager_load
    # @question = Question.includes(:answers => :user).references(:answers).find(params[:id])
  end

  def authenticate_user
    # if session[:user:id] is nil we redirect to the sign in page
    unless session[:user_id]
      redirect_to new_session_path, notice: "Please log in!"
    end
  end

  def authorize_user
    # This is a conditional where if the current_user does not match the
    # @question.user go back to the root_path
    unless can? :manage, @question #@question.user != current_user
      redirect_to root_path, alert: "access denied!"
    end
  end
end

app/helpers/api/v1/questions_helper.rb
module Api::V1::QuestionsHelper
end

app/helpers/questions_helper.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  view_count :integer
#

module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= @question.errors.full_messages.join(" ") %>

<%#  if @question is persisted then the form will send PATCH request by adding
 a hidden field with name_method and value 'patch'. The action url will be
 question_path(@question) (by convention). The form will prepopulate the
 fields with existing values for '@question' %>

 <%#  if @question is persisted then the form will send PATCH request by adding
  a hidden field with name_method and value 'patch'. The action url will be
  question_path(@question) (by convention). The form will prepopulate the
  fields with existing values for '@question' %>

<%= form_for @question do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>
<% if current_user.signed_in_with_twitter? %>
  <div>
    <%= f.check_box :tweet_it %> Tweet It.
  </div>
<% end %>
<div>
  <%= f.label :category_id %>
  <%= f.collection_select(:category_id, Category.order(:name), :id, :name) %>
</div>
<div>
  <%= f.collection_check_boxes(:tag_ids, Tag.order("name"), :id, :name) %>
</div>
<div>
  <%= f.submit %>
</div>

<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1>All Questions(<%= @questions.length %>)</h1>

<% @questions.each do |question| %>
<%= cache ["listing",question] do %>
<%# link to question pages  %>
<table class="table table-striped">
  <tr>
    <td><%= link_to question.title, question_path(question) %></td>
    <td>created by: <%= question.user_full_name %></td>
    <td>counts: <%= question.answers.count %></td>
  </tr>
</table>
<% end %>
<% end %>

app/views/questions/new.html.erb
<h1>New Questions</h1>

<%# this will look for a partial named "_form" within the same folder as
    this template (new.html.erb). The partial will have access to the instance
    varibles that this template has access to. You pass local variables by
    passing a Hash to the partial as in:
    = render "form", my_var: my_variable
    so inside the _form partial you will have a local varible defined called
    `my_var`
    %>

<%= render "form" %>

app/views/questions/show.html.erb
<%= cache @question do  %>
<h1><%= @question.title %></h1>

<p><%= @question.body %></p>

<p>View Count: <%= @question.view_count %></p>

<p><%= @question.created_at %></p>

<p>Category: <%= @question.category_name %></p>

<p>Created by: <%= @question.user_full_name%></p>

<div id="question-like">
  <%= render "/likes/question_liked" %>
</div>

<div id="question-favor">
  <%= render "/favorites/question_favor" %>
</div>

<hr>
<hr>
  <% vote = @question.vote_for(current_user) %>

  <% if !vote %>
    <%= link_to "Vote Up", question_votes_path(@question, {vote: {is_up: true}}),
                            method: :post %>

       (<%= @question.vote_result %>)
    <%= link_to "Vote Down", question_votes_path(@question, {vote: {is_up: false}}),
                            method: :post %>
  <% elsif vote.is_up? %>
    <%= link_to "Remove Vote Up", question_vote_path(@question, vote),
                            method: :delete %>
       (<%= @question.vote_result %>)
    <%= link_to "Vote Down", question_vote_path(@question, vote, {vote: {is_up: false}}),
                            method: :patch %>
  <% else %>
    <%= link_to "Vote Up", question_vote_path(@question, vote, {vote: {is_up: true}}),
                          method: :patch %>
       (<%= @question.vote_result %>)
    <%= link_to "Remove Vote Down", question_vote_path(@question, vote),
                          method: :delete %>

  <% end %>





<hr>
<% if can? :edit, @question %>
<%= link_to "Edit", edit_question_path(@question) %>
<% end %>

<%# method: :delete asks Rails to send a DELETE request instead of GET which
is accomplished using Javascript/jQuery %>
<% if can? :destroy, @question %>
<%= link_to "Delete",
            question_path(@question),
            method: :delete,
            data: {confirm: "Are you sure?"}%>
<% end %>

<%# Steps to making form_for answers %>

<h2>Answers</h2>
<h3>Create an Answer</h3>
<div id="answer-form">
  <%= render "/answers/form" %>
</div>
<%# Less ideal one %>
<%# we can use the form after overriding the 'url' parameter. The downside to it
is that it won't work for 'edit' situation. This will only work in 'create'
situation. So we can't reuse it we decide to implement editing answers. %>

<%#= form_for @answer, url: question_answers_path(@question) do |f| %>

<%# end %>



<%# @question is from what we captured from the controller
answers comes from has_many :answers method%>
<div class="answers">
  <% @question.answers.each do |ans| %>
    <%= render "/answers/answer", answer: ans %>
 <% end %>
</div>
<% end %>

app/views/questions/show.html.slim
h1= @question.title

p= @question.body

p
  | View Count: #{@question.view_count}

p= @question.created_at

p
  | Category: #{@question.category_name}

p
  | Created By: #{@question.user_full_name}

hr
#question-like= render "/likes/question_like"
hr
#question-favourite= render "favourites/question_favourite"

- vote = @question.vote_for(current_user)

- if !vote
  = link_to "Vote Up", question_votes_path(@question, {vote: {is_up: true}}),
                          method: :post
  | (#{@question.vote_result})
  = link_to "Vote Down", question_votes_path(@question, {vote: {is_up: false}}),
                          method: :post
- elsif vote.is_up?
  = link_to "Remove Vote Up", question_vote_path(@question, vote),
                          method: :delete
  | (#{@question.vote_result})
  = link_to "Vote Down", question_vote_path(@question, vote, {vote: {is_up: false}}),
                          method: :patch
- else
  = link_to "Vote Up", question_vote_path(@question, vote, {vote: {is_up: true}}),
                        method: :patch
  | (#{@question.vote_result})
  = link_to "Remove Vote Down", question_vote_path(@question, vote),
                        method: :delete
hr
- if can? :edit, @question
  = link_to "Edit", edit_question_path(@question)

- if can? :destroy, @question
  -#  method: :delete asks Rails to send a DELETE request instead of GET which is accomplished using Javascript/jQuery
  = link_to "Delete",
              question_path(@question),
              method: :delete,
              data: {confirm: "Are you sure?"}

h2 Answers
h3 Create an Answer
#answer-form= render "/answers/form"

.answers
  - @question.answers.each do |ans|
    = render "/answers/answer", answer: ans