config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get "/hello" => "welcome#index"
  get "/about" => "welcome#about"

  get "/hello/:name" => "welcome#greet", as: :greet

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  get "/questions/new" => "questions#new", as: :new_question#(this is a helper method, no need to hardcode)
  post "/questions" => "questions#create", as: :questions#(used more like a collection)

  get "/questions/:id" => "questions#show", as: :question
  get "/questions/:id/edit" => "questions#edit", as: :edit_question
  patch "/questions/:id" => "questions#update"
  delete "/questions/:id" => "questions#destroy"

  get "/questions" => "questions#index"
  resources :questions do
    get :search, on: :collection
    patch :mark_done, on: :member
    post :approve

    resources :answers, only: [:create, :destroy, :index]
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]

  end

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  namespace :api, defaults: {format: :json} do
  namespace :v1 do
    resources :questions, only: [:index, :show, :create]
  end
end

  resources :users, only: [:create, :new]

resources :sessions, only: [:new, :create, :destroy] do
  delete :destroy, on: :collection
end

resources :favorites, only: [:index]

get "/auth/twitter", as: :sign_in_with_twitter
get "/auth/twitter/callback" => "callbacks#twitter"

  root 'questions#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :user_id, :question_id, presence: true

  validates :user_id, uniqueness: { scope: :question_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user
  def index
    @question = current_user.favored_questions
  end

  def create
    @question = Question.find params[:question_id]
    favor = Favorite.new(question: @question, user: current_user)
    respond_to do |format|
      if favor.save
        format.html { redirect_to @question, notice: "Added to your favorite" }
        format.js { render :successful_favor }
      else
        format.html { redirect_to @question, alert: "like added to your favorite" }
        format.js { render :unsuccessful_favor }
      end
    end
  end

  def destroy
    @question = Question.find params[:question_id]
    favor = current_user.favorites.find params[:id] # This will ensure that only the current_user can change the favor
    favor.destroy
      respond_to do |format|
      format.html { redirect_to @question, notice: "removed" }
      format.js { render }
   end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_question_favor.html.erb
<% favor = @question.favor_for(current_user)%>
<% if favor %>
<p><%= link_to "Remove favorites", question_favorite_path(@question, favor), method: :delete, remote: true %></P>
<% else %>
<P><%= link_to "Add favorites", question_favorites_path(@question), method: :post, remote: true %></P>
<% end %>
(<%= @question.favorites.count %>)

app/views/favorites/destroy.js.erb
$('#question-favor').html('<%= j render "question_favor" %>')

app/views/favorites/index.html.erb
<h1>Favorites</h1>

<% @question.each do |question| %>
<%= link_to question.title, question_path(question) %>
<hr>
<% end %>

app/views/favorites/successful_favor.js.erb
$('#question-favor').html('<%= j render "question_favor" %>');

app/views/favorites/unsuccessful_favor.js.erb
alert("It maybe already be favored!");
window.location.reload();