config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get "/hello" => "welcome#index"
  get "/about" => "welcome#about"

  get "/hello/:name" => "welcome#greet", as: :greet

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  get "/questions/new" => "questions#new", as: :new_question#(this is a helper method, no need to hardcode)
  post "/questions" => "questions#create", as: :questions#(used more like a collection)

  get "/questions/:id" => "questions#show", as: :question
  get "/questions/:id/edit" => "questions#edit", as: :edit_question
  patch "/questions/:id" => "questions#update"
  delete "/questions/:id" => "questions#destroy"

  get "/questions" => "questions#index"
  resources :questions do
    get :search, on: :collection
    patch :mark_done, on: :member
    post :approve

    resources :answers, only: [:create, :destroy, :index]
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]

  end

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  namespace :api, defaults: {format: :json} do
  namespace :v1 do
    resources :questions, only: [:index, :show, :create]
  end
end

  resources :users, only: [:create, :new]

resources :sessions, only: [:new, :create, :destroy] do
  delete :destroy, on: :collection
end

resources :favorites, only: [:index]

get "/auth/twitter", as: :sign_in_with_twitter
get "/auth/twitter/callback" => "callbacks#twitter"

  root 'questions#index'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user

  def create
    @question = Question.find params[:question_id]
    like = Like.new(question: @question, user: current_user)
    respond_to do |format|
       if like.save
         format.html { redirect_to @question, notice: "Liked!" }
         format.js   { render :successfully_liked }
       else
         format.html { redirect_to @question, alert: "Not Liked!" }
         format.js   { render :unsuccessfully_liked };
       end
     end
   end

  def destroy
    like = current_user.likes.find params[:id]
    @question    = Question.find params[:question_id]
    like.destroy
    respond_to do |format|
       format.html { redirect_to question_path(@question), notice: "Un-liked!" }
       format.js   { render }
     end
   end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_question_liked.html.erb
<%# This is the like object for the 'current_user' and '@question' %>
<% like = @question.like_for(current_user) %>
<% if like %>
  <%= link_to "Un-like", question_like_path(@question, like), method: :delete, remote: true %>
<% else %>
<%= link_to "Like", question_likes_path(@question), method: :post, remote: true  %>
<% end %>
(<%= @question.likes.count %>)

app/views/likes/destroy.js.erb
$('#question-like').html("<%= j render 'question_liked' %>");

app/views/likes/successfully_liked.js.erb
$("#question-like").html("<%= j render 'question_liked' %>");

app/views/likes/unsuccessfully_liked.js.erb
alert("Can't like, may have been liked already!");
window.location.reload();