config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get "/hello" => "welcome#index"
  get "/about" => "welcome#about"

  get "/hello/:name" => "welcome#greet", as: :greet

  get "/subscribe" => "subscribe#index"
  post "/subscribe" => "subscribe#create"

  get "/questions/new" => "questions#new", as: :new_question#(this is a helper method, no need to hardcode)
  post "/questions" => "questions#create", as: :questions#(used more like a collection)

  get "/questions/:id" => "questions#show", as: :question
  get "/questions/:id/edit" => "questions#edit", as: :edit_question
  patch "/questions/:id" => "questions#update"
  delete "/questions/:id" => "questions#destroy"

  get "/questions" => "questions#index"
  resources :questions do
    get :search, on: :collection
    patch :mark_done, on: :member
    post :approve

    resources :answers, only: [:create, :destroy, :index]
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :votes, only: [:create, :update, :destroy]

  end

  resources :answers, only: [] do
    resources :comments, only: [:create, :destroy]
  end

  namespace :api, defaults: {format: :json} do
  namespace :v1 do
    resources :questions, only: [:index, :show, :create]
  end
end

  resources :users, only: [:create, :new]

resources :sessions, only: [:new, :create, :destroy] do
  delete :destroy, on: :collection
end

resources :favorites, only: [:index]

get "/auth/twitter", as: :sign_in_with_twitter
get "/auth/twitter/callback" => "callbacks#twitter"

  root 'questions#index'

end

app/views/layouts/application.html.erb
<!-- <%# this will be used as a default layout. %> -->
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
    body {
      margin-top: 50px;
    }
    .navbar-brand {
    padding-left: 25px;
    font-size: 25px;
    }
  </style>
</head>
<body>

<!-- <a href="/hello">Hello</a> |
<a href="/about">About</a> | -->
<%# hello_path & about_path are called route helpers. They get generated from
the content of "routes.rb" and they are methods that can be used in
all view files and all controllers %>

<!-- <a href="<%= hello_path  %>">Hello</a> | -->
<!-- <a href="<%= about_path %>">About</a>  | -->
<!-- <a href="<%= greet_path({name: "john"}) %>"> Greet John</a> -->
<!-- <a href="<%= greet_path('John') %>"> Greet John</a> -->

<%# link_to is a helper method that is built-in with rails, it's a view helper method
meaning it's accessible only in the views / view helpers. link_to
takes a first argument which is the anchor text and a second argument which
is the 'href' value (url/path). It can take other options as we will see later.
More info here:
http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <a class="navbar-left" href="#"><%= image_tag("a_logo.png") %></a>
    <a class="navbar-brand navbar-left" href="#">Awesome Answers</a>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Hello", hello_path %></li>
      <li><%= link_to "Subscribe", subscribe_path %></li>
      <li><%= link_to "New question", new_question_path %></li>
      <li><%= link_to "All Questions", root_path %></li>
    </ul>
  </div>
</nav>

<% if user_signed_in? %>
  <%= link_to "Favorites", favorites_path  %>
  Hello <%= current_user.first_name %>
  <%= link_to "Sign out", sessions_path, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_path %>
  <%= link_to "Sign In With Twitter", sign_in_with_twitter_path %>
  <%= link_to "Sign up", new_user_path %>
<% end %>


<%# Both of the lines serves same purpose
line 39 is a shorter version of calling flash method(like session, built in ruby)  %>
<%#= flash[:notice] || flash[:alert] %>
<%= notice || alert %>
<%= yield %>

</body>
</html>